name: Docker Image

on:
  push:
    paths:
      - docker/dockerfile
      - docker/docker-compose*.yml

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Build a Docker image able to run yeswiki
        run: export UID=$(id -u) && export GID=$(id -g) && docker build -f docker/dockerfile -t yeswiki/yeswiki .
